name: mirror-content

on:
  push:
    branches:
      - main

jobs:

  mirror-to-binder-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: tuftsrt/branch-manager@develop
        with:
          destination-branch: binder
          clear-destination: "true"
          copy: |
            binder/|.binder
            workshop/|
          replace: |
            GH_ACTIONS_DATE|${{ steps.date.outputs.date }}|*.R

  mirror-to-workshop-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: date
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - uses: tuftsrt/branch-manager@develop
        with:
          destination-branch: workshop
          clear-destination: "true"
          copy: |
            workshop/|
          replace: |
            GH_ACTIONS_DATE|${{ steps.date.outputs.date }}|*.R
